
CREATE OR REPLACE DYNAMIC TABLE MAIN.DT_VEHICLE_TELEMATICS_SILVER
TARGET_LAG = '1 MINUTES'
WAREHOUSE = SNOWIOT_WH
AS

WITH BronzeFlattened AS(
	SELECT
			tvd.value:id::INT AS ID
			,tvd.value:vin::STRING AS VIN
			,tvd.value:PUBLISH_TIME::STRING AS PUBLISH_TIME
			,tvd.value:eventCd::STRING AS EVENTCD
			,tvdd.value:name::STRING AS FIELD_NAME
			,CONVERT_TIMEZONE('UTC',current_timestamp()) as EVENT_READ_SNOWFLAKE_SILVER_TIMESTAMP
			,tvdd.value:uom::STRING AS FIELD_UOM
			,tvdd.value:val::STRING AS FIELD_VALUE
	FROM MAIN.VEHICLE_TELEMATICS_BRONZE
		,LATERAL FLATTEN(RECORD_CONTENT, path => 'tripvehicledata') tvd
		,LATERAL FLATTEN(tvd.value:data) tvdd
)
,FieldNamePivot AS (
    SELECT
         ID
        ,VIN
        ,PUBLISH_TIME
        ,EVENTCD
		,EVENT_READ_SNOWFLAKE_SILVER_TIMESTAMP
        ,"'AGEIND'" AS AGEIND
        ,"'CURRENT_SPEED'" AS CURRENT_SPEED
        ,"'CURRENT_SPEED_VALIDITY'" AS CURRENT_SPEED_VALIDITY
        ,"'DIR'"AS DIR
        ,"'DRIVER_SEATBELT_INDICATOR'"AS DRIVER_SEATBELT_INDICATOR
        ,"'EHPE'"AS EHPE
        ,"'ELV'" AS ELV
        ,"'ENGINE_RUN_TIME_TOTAL'"AS ENGINE_RUN_TIME_TOTAL
        ,"'ENG_IDLE_RUN_TIME_TOTAL'"AS ENG_IDLE_RUN_TIME_TOTAL
        ,"'ENG_IDL_RUNT_TOTSUP'"AS ENG_IDL_RUNT_TOTSUP
        ,"'ENG_RUNT_PTO_ACT_TOTSUP'"AS ENG_RUNT_PTO_ACT_TOTSUP
        ,"'ENG_RUN_TME_PTO_ACT_TOT'"AS ENG_RUN_TME_PTO_ACT_TOT
        ,"'ENG_RUN_TOTSUP'"AS ENG_RUN_TOTSUP
        ,"'FUEL_USED'"AS FUEL_USED
        ,"'IGN_CYL'"AS IGN_CYL
        ,"'LAT'"AS LAT
        ,"'LNG'"AS LNG
        ,"'LOCATION_TIME_OFFSET'"AS LOCATION_TIME_OFFSET
        ,"'ODO_READ'"AS ODO_READ
        ,"'SPDINKM'"AS SPDINKM
        ,"'SPEED_RATE_OF_CHANGE'"AS SPEED_RATE_OF_CHANGE
        ,"'SPEED_RATE_OF_CHANGE_POSITIVE'"AS SPEED_RATE_OF_CHANGE_POSITIVE
        ,"'SYSTEM_POWER_MODE'"AS SYSTEM_POWER_MODE
    FROM (
			SELECT
				 ID
				,VIN
				,PUBLISH_TIME
				,EVENT_READ_SNOWFLAKE_SILVER_TIMESTAMP
				,EVENTCD
				,FIELD_NAME
				,FIELD_VALUE
			FROM BronzeFlattened
		) AS Source
    PIVOT (
				MAX(FIELD_VALUE)  
				FOR FIELD_NAME IN (
					'AGEIND', 'CURRENT_SPEED', 'CURRENT_SPEED_VALIDITY', 'DIR',
					'DRIVER_SEATBELT_INDICATOR', 'EHPE', 'ELV', 'ENGINE_RUN_TIME_TOTAL',
					'ENG_IDLE_RUN_TIME_TOTAL', 'ENG_IDL_RUNT_TOTSUP', 'ENG_RUNT_PTO_ACT_TOTSUP',
					'ENG_RUN_TME_PTO_ACT_TOT', 'ENG_RUN_TOTSUP', 'FUEL_USED', 'IGN_CYL',
					'LAT', 'LNG', 'LOCATION_TIME_OFFSET', 'ODO_READ', 'SPDINKM',
					'SPEED_RATE_OF_CHANGE', 'SPEED_RATE_OF_CHANGE_POSITIVE', 'SYSTEM_POWER_MODE'
				)
			)
)
,FieldNameUomPivot AS (
    SELECT
         ID
        ,VIN
        ,PUBLISH_TIME
        ,EVENTCD
        ,"'AGEIND'" AS AGEIND_UOM
        ,"'CURRENT_SPEED'" AS CURRENT_SPEED_UOM
        ,"'CURRENT_SPEED_VALIDITY'" AS CURRENT_SPEED_VALIDITY_UOM
        ,"'DIR'"AS DIR_UOM
        ,"'DRIVER_SEATBELT_INDICATOR'"AS DRIVER_SEATBELT_INDICATOR_UOM
        ,"'EHPE'"AS EHPE_UOM
        ,"'ELV'"AS ELV_UOM
        ,"'ENGINE_RUN_TIME_TOTAL'"AS ENGINE_RUN_TIME_TOTAL_UOM
        ,"'ENG_IDLE_RUN_TIME_TOTAL'"AS ENG_IDLE_RUN_TIME_TOTAL_UOM
        ,"'ENG_IDL_RUNT_TOTSUP'"AS ENG_IDL_RUNT_TOTSUP_UOM
        ,"'ENG_RUNT_PTO_ACT_TOTSUP'"AS ENG_RUNT_PTO_ACT_TOTSUP_UOM
        ,"'ENG_RUN_TME_PTO_ACT_TOT'"AS ENG_RUN_TME_PTO_ACT_TOT_UOM
        ,"'ENG_RUN_TOTSUP'"AS ENG_RUN_TOTSUP_UOM
        ,"'FUEL_USED'"AS FUEL_USED_UOM
        ,"'IGN_CYL'"AS IGN_CYL_UOM
        ,"'LAT'"AS LAT_UOM
        ,"'LNG'"AS LNG_UOM
        ,"'LOCATION_TIME_OFFSET'"AS LOCATION_TIME_OFFSET_UOM
        ,"'ODO_READ'"AS ODO_READ_UOM
        ,"'SPDINKM'"AS SPDINKM_UOM
        ,"'SPEED_RATE_OF_CHANGE'"AS SPEED_RATE_OF_CHANGE_UOM
        ,"'SPEED_RATE_OF_CHANGE_POSITIVE'"AS SPEED_RATE_OF_CHANGE_POSITIVE_UOM
        ,"'SYSTEM_POWER_MODE'"AS SYSTEM_POWER_MODE_UOM
    FROM (
			SELECT
				 ID
				,VIN
				,PUBLISH_TIME
				,EVENTCD
				,FIELD_NAME
				,FIELD_UOM
			FROM BronzeFlattened
		) AS Source
    PIVOT (
			MAX(FIELD_UOM)  
			FOR FIELD_NAME IN (
								'AGEIND', 'CURRENT_SPEED', 'CURRENT_SPEED_VALIDITY', 'DIR',
								'DRIVER_SEATBELT_INDICATOR', 'EHPE', 'ELV', 'ENGINE_RUN_TIME_TOTAL',
								'ENG_IDLE_RUN_TIME_TOTAL', 'ENG_IDL_RUNT_TOTSUP', 'ENG_RUNT_PTO_ACT_TOTSUP',
								'ENG_RUN_TME_PTO_ACT_TOT', 'ENG_RUN_TOTSUP', 'FUEL_USED', 'IGN_CYL',
								'LAT', 'LNG', 'LOCATION_TIME_OFFSET', 'ODO_READ', 'SPDINKM',
								'SPEED_RATE_OF_CHANGE', 'SPEED_RATE_OF_CHANGE_POSITIVE', 'SYSTEM_POWER_MODE'
							)
		)
)


SELECT DISTINCT
     fnp.ID
    ,fnp.VIN
    ,fnp.PUBLISH_TIME
	,fnp.EVENT_READ_SNOWFLAKE_SILVER_TIMESTAMP
    ,fnp.EVENTCD
    ,fnp.AGEIND
    ,fnup.AGEIND_UOM
    ,fnp.CURRENT_SPEED
    ,fnup.CURRENT_SPEED_UOM
    ,fnp.CURRENT_SPEED_VALIDITY
    ,fnup.CURRENT_SPEED_VALIDITY_UOM
    ,fnp.DIR
    ,fnup.DIR_UOM
    ,fnp.DRIVER_SEATBELT_INDICATOR
    ,fnup.DRIVER_SEATBELT_INDICATOR_UOM
    ,fnp.EHPE
    ,fnup.EHPE_UOM
    ,fnp.ELV
    ,fnup.ELV_UOM
    ,fnp.ENGINE_RUN_TIME_TOTAL
    ,fnup.ENGINE_RUN_TIME_TOTAL_UOM
    ,fnp.ENG_IDLE_RUN_TIME_TOTAL
    ,fnup.ENG_IDLE_RUN_TIME_TOTAL_UOM
    ,fnp.ENG_IDL_RUNT_TOTSUP
    ,fnup.ENG_IDL_RUNT_TOTSUP_UOM
    ,fnp.ENG_RUNT_PTO_ACT_TOTSUP
    ,fnup.ENG_RUNT_PTO_ACT_TOTSUP_UOM
    ,fnp.ENG_RUN_TME_PTO_ACT_TOT
    ,fnup.ENG_RUN_TME_PTO_ACT_TOT_UOM
    ,fnp.ENG_RUN_TOTSUP
    ,fnup.ENG_RUN_TOTSUP_UOM
    ,fnp.FUEL_USED
    ,fnup.FUEL_USED_UOM
    ,fnp.IGN_CYL
    ,fnup.IGN_CYL_UOM
    ,fnp.LAT
    ,fnup.LAT_UOM
    ,fnp.LNG
    ,fnup.LNG_UOM
    ,fnp.LOCATION_TIME_OFFSET
    ,fnup.LOCATION_TIME_OFFSET_UOM
    ,fnp.ODO_READ
    ,fnup.ODO_READ_UOM
    ,fnp.SPDINKM
    ,fnup.SPDINKM_UOM
    ,fnp.SPEED_RATE_OF_CHANGE
    ,fnup.SPEED_RATE_OF_CHANGE_UOM
    ,fnp.SPEED_RATE_OF_CHANGE_POSITIVE
    ,fnup.SPEED_RATE_OF_CHANGE_POSITIVE_UOM
    ,fnp.SYSTEM_POWER_MODE
    ,fnup.SYSTEM_POWER_MODE_UOM
FROM 
FieldNamePivot fnp 
JOIN 
FieldNameUomPivot fnup 
ON fnp.ID = fnup.ID AND fnp.VIN = fnup.VIN AND  fnp.EVENTCD = fnup.EVENTCD ;










CREATE OR REPLACE DYNAMIC TABLE MAIN.DT_VEHICLE_TELEMATICS_GOLD
TARGET_LAG = '2 MINUTES'
WAREHOUSE = SNOWIOT_WH
AS
SELECT 
    ID
	,VIN
    ,SUM(CASE WHEN EVENTCD= 'HardBrake' THEN 1 ELSE 0 END) AS NO_OF_TIMES_HARDBRAKE
    ,SUM(CASE WHEN EVENTCD= 'HardAcceleration' THEN 1 ELSE 0 END) AS NO_OF_TIMES_HARDACCELERATION
    ,SUM(CASE WHEN DRIVER_SEATBELT_INDICATOR = 'UNLATCHED' THEN 1 ELSE 0 END) AS COUNT_SEATBELT_UNLATCHED
    ,SUM(CASE WHEN CURRENT_SPEED_VALIDITY = 'INVALID' THEN 1 ELSE 0 END) AS COUNT_INVALID_SPEED
	,AVG(NULLIF(CASE WHEN EVENTCD = 'HardAcceleration' THEN CURRENT_SPEED ELSE 0 END, 0)) AS SPEED_HARDACCELERATION
	,AVG(NULLIF(CASE WHEN EVENTCD = 'HardBrake' THEN CURRENT_SPEED ELSE 0 END, 0)) AS SPEED_HARDBRAKE
    ,SUM(CASE WHEN EVENTCD = 'TripEnd' THEN ODO_READ ELSE 0 END) - SUM(CASE WHEN EVENTCD = 'TripStart' THEN ODO_READ ELSE 0 END) AS ODO_DISTANCE
FROM MAIN.DT_VEHICLE_TELEMATICS_SILVER
GROUP BY 
	 ID
	,VIN	;